<?php
/**
 * OpenGraph module.
 *
 * This module implements the Open Graph protocol for Drupal.
 *
 * @link http://ogp.me/
 */

/**
 * Add an opengraph property to the <head> section.
 *
 * Before acutally adding the property, this function first checks if the
 * selected namespace has been defined. If the namespace is not available,
 * the property is discarded.
 *
 * @param string $property
 *     The name of the property.
 * @param string $value
 *     The value of the property.
 * @param string $namespace
 *     The namespace of the property. Defaults to 'og'.
 *
 * @return array
 *     The currently set properties.
 */
function opengraph_set_property($property = '', $value = '', $namespace = 'og')
{
    static $properties = array();

    // List of properties that can be set as arrays.
    $array_properties = array(
        'image',
        'tag',
        'author', // book, article: {profile}s
        'album', // song: {music.album}s
        'musician', // song: {profile}s
        'song', // music.playlist, music.album: {music.song}s
        'actor', // video.*: {profile}s
        'director', // video.*: {profile}s
        'write', // video.*: {profile}s
    );

    if (!empty($property) && !empty($value)) {
        // some properties allows for multiple instances
        if (in_array($property, $array_properties)) {
            $properties[$namespace][$property][] = $value;
        }
        else {
            $properties[$namespace][$property] = $value;
        }
    }

    return $properties;
}

/**
 * Configure the menu items for the Open Graph module.
 *
 * @return array
 *     The menu items.
 *
 * @seealso hook_menu()
 */
function opengraph_menu()
{
    $menu = array();
    $menu['admin/settings/opengraph'] = array(
        'title' => 'Open Graph',
        'description' => 'Edit basic Open Graph aware information.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('opengraph_site_information'),
        'access arguments' => array('administer site configuration'),
        'file' => 'opengraph.admin.inc',
    );

    return $menu;
}

/**
 * Define the Open Graph information block.
 *
 * @param string $op
 *     The operation to perform.
 * @param string $delta
 *     The identifier of the block to perform the operation on.
 * @param array $edit
 *     The form data submitted when the block is configured.
 *
 * @return array
 *     The data required by the operation, if applicable.
 *
 * @seealso hook_block()
 */
function opengraph_block($op = 'list', $delta = '', $edit = array())
{
    switch ($op) {
        case 'list':
            return array(
                'information' => array(
                    'info' => t('Open Graph Information'),
                    'cache' => BLOCK_CACHE_GLOBAL,
                ),
            );

        case 'view':
            return opengraph_block_content();
    }
}

/**
 * Request the content for the block identified by $delta.
 *
 * @return array
 *     An array with the subject and content of the block.
 */
function opengraph_block_content()
{
    $content = "<address>\n";
    
    // Name of Open Graph object's website
    if ($site_name = variable_get('site_name', false)) {
        $content .= '<h4 class="site-name">'.$site_name."</h4>\n";
    }

    // Address of Open Graph object
    if ($locality = variable_get('opengraph_locality', false)) {
        // Add the address
        if ($street_address = variable_get('opengraph_street_address', false)) {
            $content .= $street_address."<br />\n";
        }

        // Add the postal code
        if ($postal_code = variable_get('opengraph_postal_code', false)) {
            $content .= $postal_code.' ';
        }
        $content .= $locality."<br />\n";

        // Add the country
        if ($country_name = variable_get('opengraph_country_name', false)) {
            $content .= $country_name."<br />\n";
        }
    }

    // Contact details of Open Graph object
    if ($site_mail = variable_get('site_mail', false)) {
        $content .= '<a class="email" href="mailto:'.$site_mail.'">'.$site_mail."</a><br />\n";
    }
    if ($phone_number = variable_get('opengraph_phone_number', false)) {
        $content .= '<span class="phone-number">'.$phone_number."</span><br />\n";
    }

    $content .= "</address>\n";

    return array(
        'subject' => t('Contact'),
        'content' => $content,
    );
}

/**
 * Add default Open Graph Protocol information.
 *
 * Some of this information will be overwritten by other parts of the module, when applicable.
 *
 * @seealso hook_init()
 */
function opengraph_init()
{
    global $theme_key, $base_path;
    // We need to emulate init_theme() because it has not run yet.
    $theme_key = variable_get('theme_default', 'garland');

    // Set default properties
    opengraph_set_property('type', variable_get('opengraph_type', 'website'));
    opengraph_set_property('title', variable_get('site_name', 'Drupal'));

    opengraph_set_property('url', url($_GET['q'], array('absolute' => true)));
    opengraph_set_property('site_name', variable_get('site_name', 'Drupal'));
    opengraph_set_property('image', url(substr(theme_get_setting('logo'), strlen($base_path)), array('absolute' => true)));

    opengraph_set_property('locale', opengraph_get_language());

    // Set extended properties
    $properties = array(
        'description',
    );
    foreach ($properties as $property) {
        $value = variable_get('opengraph_' . str_replace('-', '_', $property), null);
        if (empty ($value)) {
            continue;
        }

        opengraph_set_property($property, $value);
    }

    drupal_add_css(drupal_get_path('module', 'opengraph') . '/opengraph.css');
}

/**
 * Adds additional namespaces to the page for use with the Open Graph Protocol.
 *
 * @return array
 *     The namespaces used by the OpenGraph module.
 *
 * @seealso hook_namespaces()
 */
function opengraph_namespaces()
{
    return array(
        'og' => 'http://ogp.me/ns',
        'music' => 'http://ogp.me/ns/music',
        'video' => 'http://ogp.me/ns/video',
        'article' => 'http://ogp.me/ns/article',
        'book' => 'http://ogp.me/ns/book',
        'profile' => 'http://ogp.me/ns/profile',
        'website' => 'http://ogp.me/ns/website',
        'drupal' => 'http://www.drupal.org/ns',
    );
}

/**
 * Adds Open Graph properties to user pages.
 *
 * @param string $op
 *     The current operation on the $account object.
 * @param array $edit
 *     The data submitted during editing of the $account.
 * @param object $account
 *     The account that is being processed.
 * @param string $category
 *     The category for which $account is being edited.
 *
 * @seealso hook_user()
 */
function opengraph_user($op, &$edit, &$account, $category = '') {
    if ($op == 'view') {
        opengraph_set_property('type', 'profile');

        opengraph_set_property('title', $account->name);
        opengraph_set_property('username', $account->name, 'profile');

        if (!empty($account->picture)) {
            opengraph_set_property('image', $account->picture);
        }
    }
}

/**
 * Adds Open Graph properties to nodes when it is the main item on the page viewed.
 *
 * @param object $node
 *     The node object that is being processed.
 * @param string $op
 *     The current operation for node processing.
 * @param mixed $a3
 *     When viewing a node: whether the node viewed is being viewed as a teaser.
 *     When validating a node: the form that was used to edit the node.
 * @param bool $a4
 *     When viewing a node: whether the node viewed is being viewed is the main item on the page.
 *
 * @seealso hook_nodeapi()
 */
function opengraph_nodeapi(&$node, $op, $a3 = null, $a4 = false) {
    if ($op == 'view' && $a4) {
        opengraph_set_property('type', 'article');
        opengraph_set_property('title', $node->title);
        opengraph_set_property('author', url('user/'.$node->uid, array('absolute' => true)), 'article');
        opengraph_set_property('published_time', gmdate('c', $node->created), 'article');
        opengraph_set_property('modified_time', gmdate('c', $node->changed), 'article');
    }
}

/**
 * Updates the $head variable with all set Open Graph properties.
 *
 * @param array $variables
 *     The variables to use in the page.tpl.php template.
 *
 * @seealso template_preprocess_page()
 */
function opengraph_preprocess_page(&$variables) {
    $graph = opengraph_set_property();

    $meta = '<meta property="%s:%s" content="%s">';

    foreach ($graph as $namespace => $properties) {
        foreach ($properties as $property => $value) {
            if (is_array($value)) {
                foreach ($value as $item) {
                    drupal_set_html_head(sprintf($meta, $namespace, $property, $item));
                }
            }
            else {
                drupal_set_html_head(sprintf($meta, $namespace, $property, $value));
            }
        }
    }
    
    // Update the $head variable.
    $variables['head'] = drupal_get_html_head();
}

/**
 * Append a common ISO3166 territory identifier to the ISO639 language identifier.
 *
 * @return string
 *     The formatted language code.
 *
 * @todo Add support for other languages.
 */
function opengraph_get_language() {
    $language = user_preferred_language($GLOBALS['user']);

    switch($language->language) {
        case 'nl':
            return 'nl_NL';
        case 'en':
        default:
            return 'en_US';
    }
}